spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tyrival/SpringCloudConfig.git
          username:
          password:

server:
  port: 9901