server:
  port: 9001

spring:
  application:
    name: server-eureka

eureka:
  instance:
    hostname: localhost
    context: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/${eureka.instance.context}/
