eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

spring:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      # 节点地址，多个节点用逗号隔开，REST模式为9200，API模式的端口为9300
      cluster-nodes: 127.0.0.1:9200,127.0.0.2:9200
      repositories:
        enable: true
  application:
    name: server-vision
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: 123
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    root: debug
  attachment: datacenter-log/vision-log:log

# 附件上传的根文件夹名
attachment:
  rootPath: attachment