eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

spring:
  application:
    name: server-elastic
  data:
    elasticsearch:
      cluster-name: docker-cluster
      # 节点地址，多个节点用逗号隔开，REST模式为9200，API模式的端口为9300
      cluster-nodes: 127.0.0.1:9200
      repositories:
        enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

logging:
  level:
    root: debug
  attachment: vision-log/elastic-log:log