eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

spring:
  #redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123
    # 连接超时时间（毫秒）
    timeout: 2000ms
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  cache:
    type: redis
  application:
    name: server-system
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: 123
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: admin
#    password: admin
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    root: debug
  attachment: datacenter-log/system-log:log

# 附件上传的根文件夹名
attachment:
  rootPath: attachment