eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

zuul:
  ribbon:
    eager-load:
      enabled: true
  routes:
    vision:
      path: /**
      serviceId: server-feign
  max:
    host:
      connections: 500
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
#        timeout:
#          enabled: false
#feign:
#  hystrix:
#    enabled: true

filter:
  token:
    excludeUri: /user/login,/attachment/download

logging:
  level:
    root: debug
  file: vision-log/zuul-log:log

spring:
  application:
    name: server-zuul
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1