eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

zuul:
  routes:
    vision:
      path: /**
      serviceId: server-feign
  max:
    host:
      connections: 500
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
#        timeout:
#          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#feign:
#  hystrix:
#    enabled: true

filter:
  token:
    excludeUri: /user/login,/attachment/download

logging:
  level:
    root: debug
  file: vision-log/zuul-log:log

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1