eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true

ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
  eager-load:
    enabled: true
    clients:
      - service-system
      - service-vision
      - service-datasource
#  # 请求重试次数，可防止网络抖动，但需要防止新增接口出现多次数据插入的情况
#  OkToRetryOnAllOperations: true
#  MaxAutoRetries: 1
#  MaxAutoRetriesNextServer: 1

logging:
  level:
    root: debug
  file: vision-log/feign-log.log

spring:
  application:
    name: server-feign
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000