eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  hystrix:
    enabled: true

logging:
  level:
    root: debug
  file: vision-log/feign-log:log

spring:
  application:
    name: server-feign
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000